title: Veneesh
logo: /assets/img/IMG_20210221_114714_473.jpg
description: I am currently pursuing Executive PG in ML & Artificial intelligence.
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
